version: '3'

services:
  my-elast:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.1
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./elasticsearch:/usr/share/elasticsearch/data
    environment:
      - "discovery.type=single-node"

volumes:
  elast_data: